print("WELCOME TO OUR WEBSITE")
cet = int(input("ENTER YOUR CET MARKS(only PCM) : "))
p = int(input("ENTER YOUR PHYSICS PU MARKS : "))
c = int(input('ENTER YOUR CHEMISTRY PU MARKS : '))
m = int(input("ENTER YOUR MATHEMATICS PU MARKS : "))
total = ( p + c + m )
per1 = (total/300*100)
puc = (total/300 * 100 )
print(f"TOTAL : {total}")
print(f"YOUR PUC PERCENTAGE (only PCM) : {per1}" )
puc2 = (puc/2)
print(f"HALF OF YOUR PERCENTAGE : {puc2}")
cet_p =(cet/141*100)
cetp2 = (cet_p/2)
t_perce = (puc2 + cetp2)
print(f"YOUR CET PERCENTAGE : {cet_p} ")
print(f"HALF OF YOUR CET PERCENTAGE : {cetp2}")
print(f"TOTAL PERCENTAGE(PUC+CET) : { t_perce }")
